---
title: "NL_Gold"
author: "Nankun"
date: "2019/12/2"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


notice: Gold difference - computed Blue minus Red


```{r}
#import#
gold = read_csv(file = "./data/gold.csv")
#cleaning#
gold_cl = 
  gold %>% 
  janitor::clean_names() %>% 
  filter(type == "golddiff") %>% 
  mutate(
    address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")
  ) %>% 
  pivot_longer(
  min_1:min_95,
  names_to = "min", 
  names_prefix = "min_",
  values_to = "gold") %>% 
  drop_na()

gold_ave =
  gold_cl %>% 
  group_by(address) %>% 
  summarize(
    golddiff_mean = mean(gold)
  )

```

combine

```{r}
overall = 
  read_csv(file = "./data/LeagueofLegends.csv") %>% 
  janitor::clean_names() %>% 
  mutate(address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")) %>% 
  select(address, b_result)

gold_mg = 
  left_join(overall, gold_ave, by = "address") %>% 
  mutate(b_result = recode_factor(b_result, "1" = "win", "0" = "lose"))

```

Plot

```{r}
gold_mg %>% 
  ggplot(aes(x = b_result, y = golddiff_mean)) + 
  geom_boxplot()
```

## logistic model

```{r}
gold_log = gold_mg %>% 
  glm(formula =  b_result ~ golddiff_mean, family = "binomial")
 
gold_log %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

gold_log %>% 
  broom::glance() %>% 
  knitr::kable(digits = 3)
```

