---
title: "ziyang_data_cleaning"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
```

# 清理数据,计算每局比赛中各种野怪的击杀数量

```{r}
monster = read_csv("./leagueoflegends/monsters.csv")

str(monster)
summary(monster)

monster = monster %>% 
  filter(Team %in% c("bDragons", "bBarons", "bHeralds")) %>% 
  group_by(Address, Type) %>% 
  summarize(number = n()) %>% 
  pivot_wider(
    names_from = Type,
    values_from = number
  ) 

monster[is.na(monster)] = 0

monster = monster %>% 
  janitor::clean_names()
```

# 将刚才清洗的数据与总体数据做合并

```{r}
overall = read_csv("./leagueoflegends/LeagueofLegends.csv") %>% 
  janitor::clean_names()

newdata = right_join(overall, monster, by = "address") %>% 
  select(year, b_result, address:dragon)
```

# 尝试建立模型

```{r}
logistic_model = newdata %>% 
  mutate(b_result = factor(b_result)) %>% 
  glm(formula =  b_result ~ air_dragon + water_dragon + fire_dragon + earth_dragon + elder_dragon + rift_herald + baron_nashor + dragon, family = "binomial")
 
logistic_model %>% broom::tidy()

logistic_model %>% broom::glance()
```

# 尝试做一些可视化

```{r}
blank_theme <- theme_minimal() +
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.ticks = element_blank(),
  plot.title = element_text(size = 14, face = "bold")
  )

overall %>% 
  select(b_result, r_result) %>% 
  mutate(b_wins = sum(b_result), r_wins = sum(r_result), total = b_wins + r_wins) %>% 
  select(b_wins:total) %>%
  pivot_longer(
    b_wins:r_wins,
    names_to = "team",
    values_to = "game_won"
  ) %>% 
  filter(row_number() <= 2) %>% 
  ggplot(aes(x = "", y = game_won, fill = team)) +
  geom_bar(stat = "identity", width = 1) +
  geom_text(aes(label = percent(game_won / total)), position = position_stack(vjust = 0.5)) +
  coord_polar("y") +
  labs(  
    title = "Win rates of Blue and Red teams across all years"
  ) +
  scale_fill_manual(labels = c("Blue", "Red"), values = c("cadetblue1", "coral1")) + 
  blank_theme +
  theme(axis.text.x = element_blank())
```
